force-app/main/default/objects/Chat_Message__c/Chat_Message__c.object-meta.xml
<CustomObject>
    <label>Chat Message</label>
    <nameField>
        <label>Chat Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Message__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of the chat message.</description>
    <label>Content</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ChatController.cls
public with sharing class ChatController {
    @AuraEnabled(cacheable=true)
    public static List<Chat_Message__c> getTodayMessages() {
        List<Chat_Message__c> messageList;

        try {
            messageList = [
                SELECT Id, Content__c, CreatedBy.Name
                FROM Chat_Message__c 
                WHERE createdDate = today 
                ORDER BY CreatedDate DESC
            ];
        } catch(Exception e) {
            System.debug(e.getMessage());
            return null;
        }
        return messageList;
    }
}